feat: execute tests in headless mode
vaadin/addon-starter-flow pull request #282
Opened 2023-04-19 08:10 UTC by mcollovati

## Description

Prevents browser windows to be opened when executing tests. However, headless mode is always deactivated when running the test in debug mode.

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-04-24 11:53 UTC, tltv requested changes

2023-04-24 11:53 UTC, tltv commented on README.md
> +or when running maven with the `-Dmaven.failsafe.debug` sytem property.
```suggestion
or when running maven with the `-Dmaven.failsafe.debug` system property.
```

2023-04-24 11:53 UTC, tltv commented on src/test/java/org/vaadin/addons/mygroup/AbstractViewTest.java
> +     * @param themeClass theme class (such as {@code Lumo.class}
```suggestion
     * @param themeClass theme class (such as {@code Lumo.class})
```

2023-04-25 07:23 UTC, tltv approved these changes

2023-05-08 11:43 UTC, czp13 approved these changes

2023-05-08 11:46 UTC, czp13 commented
Probably would be good to test this manually to see if tests are working in all the ways (debug, property, without those).

2023-05-08 13:09 UTC, mcollovati commented
I did all the mentioned tests locally. It's quite easy to do it if you want to double check all is working as expected

2023-05-10 08:14 UTC, mcollovati commented
@samie @mstahv, do you mind taking a look at this?

2023-05-10 08:25 UTC, mstahv approved these changes
Looks good to me!

2023-05-10 08:28 UTC, merged